// demo-vue/app/components/Home.vue
<template>
  <Page class="page">
    <ActionBar class="action-bar">
      <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>

    <GridLayout>
      <StackLayout class="p-20">
        <Button text="show" class="t-20 text-center c-black" @tap="onTap"></Button>
      </StackLayout>
    </GridLayout>
  </Page>
</template>

<script>
import {
  CustomBottomsheet,
  CBSheetOption
} from "nativescript-custom-bottomsheet";

import { alert } from "tns-core-modules/ui/dialogs";

const customBottomsheet = new CustomBottomsheet();

export default {
  methods: {
    onTap() {
      const options = {
        icon: "contact",
        title: "John Doe",
        items: [
          {
            icon: "call",
            title: "Make a call"
          },
          {
            icon: "sms",
            title: "Send a text message"
          },
          {
            icon: "email",
            title: "Send an email"
          },
          {
            icon: "comments",
            title: "Leave a comment"
          },
          {
            icon: "delete",
            title: "Delete contact"
          }
        ],
        onItemTap: (index, item) => {
          console.log("index", index);
          if (item) {
            alert(`Action Selected : "${item.title}"`);
          }
        },
        cancelButtonText: "Cancel"
      };

      this.customBottomsheet.show(options);
    }
  }
};
</script>

<style scoped lang="scss">
// Start custom common variables
@import "../app-variables";
// End custom common variables

// Custom styles
.fa {
  color: $accent-dark;
}

.info {
  font-size: 20;
}
</style>

// demo-ng/src/app/home/home.component.ts
import { Component, OnInit, NgZone } from "@angular/core";
import { CustomBottomsheet, CBSheetOption, CBSheetItem } from 'nativescript-custom-bottomsheet';
import { alert } from "tns-core-modules/ui/dialogs";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    private customBottomsheet: CustomBottomsheet;

    constructor(private zone: NgZone) {
        // Use the component constructor to inject providers.
        this.customBottomsheet = new CustomBottomsheet();
    }

    ngOnInit(): void {
        // Init your component properties here.
    }

    public onTap(): void {
        const options: CBSheetOption = {
            icon: 'contact',
            title: 'John Doe',
            items: [
                {
                    icon: 'call',
                    title: 'Make a call'
                },
                {
                    icon: 'sms',
                    title: 'Send a text message'
                },
                {
                    icon: 'email',
                    title: 'Send an email'
                },
                {
                    icon: 'comments',
                    title: 'Leave a comment'
                },
                {
                    icon: 'delete',
                    title: 'Delete contact'
                }
            ],
            onItemTap: (index, item) => {
                this.zone.run(() => {
                    console.log('index', index);
                    if (item) {
                        alert(`Action Selected => "${item.title}"`);
                    }
                })
            },
            cancelButtonText: 'Cancel'
        };


        this.customBottomsheet.show(options);
    }
}

<ActionBar class="action-bar">
    <Label class="action-bar-title" text="Home"></Label>
</ActionBar>

<GridLayout class="page">
    <StackLayout class="p-20">
        <Button text="show" class="t-20 text-center c-black" (tap)="onTap()"></Button>
    </StackLayout>
</GridLayout>
